# Generated by Django 5.1.3 on 2024-11-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='classes',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
