# Generated by Django 5.1.3 on 2024-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_button_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
